# Generated by Django 5.2.8 on 2025-11-11 22:14

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("rework", "Rework"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "last_published_revision_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("live_i18n", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True, related_name="usecases", to="catalog.tool"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usecase",
                "verbose_name_plural": "Usecases",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UseCaseTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("intro", models.TextField(blank=True, verbose_name="Intro")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                ("outro", models.TextField(blank=True, verbose_name="Outro")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                (
                    "public_slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        null=True,
                        unique=True,
                        verbose_name="Public slug",
                    ),
                ),
                ("persona", models.CharField(max_length=100, verbose_name="Persona")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="usecases.usecase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usecase Translation",
                "db_table": "usecases_usecase_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
