# Generated by Django 5.2.9 on 2026-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usecases", "0004_alter_usecase_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
