title: "[Suspected Bug] "
labels: [ "needs-triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Not sure if this is a real bug?  
        Describe it here and we’ll help decide whether to create a GitHub Issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the behavior you observed.
      placeholder: "When I switch the language on…, I see…"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: "I expected it to redirect to the translated detail page…"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if known)
      description: List steps so others can reproduce the issue.
      placeholder: |
        1. Go to …
        2. Click …
        3. See …
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / error messages (optional)
      description: Paste any relevant logs or screenshots.
    validations:
      required: false
