# Generated by Django 5.2.8 on 2025-11-11 22:14

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("rework", "Rework"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                (
                    "last_published_revision_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("live_i18n", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="catalog.category"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tools", models.ManyToManyField(blank=True, to="catalog.tool")),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("live_i18n", models.JSONField(blank=True, default=dict)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Section",
                "verbose_name_plural": "Guide Sections",
                "ordering": ["order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuideItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("prompt", "Prompt"),
                            ("usecase", "UseCase"),
                            ("tool", "Tool"),
                            ("comparison", "Comparison"),
                        ],
                        default="guide",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "guides"), ("model", "guide")),
                            models.Q(("app_label", "prompts"), ("model", "prompt")),
                            models.Q(("app_label", "usecases"), ("model", "usecase")),
                            models.Q(("app_label", "catalog"), ("model", "tool")),
                            models.Q(("app_label", "compare"), ("model", "comparison")),
                            _connector="OR",
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="guides.guidesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Item",
                "verbose_name_plural": "Guide Items",
                "ordering": ["order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuideSectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="guides.guidesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Section Translation",
                "db_table": "guides_guidesection_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuideTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("intro", models.TextField(blank=True, verbose_name="Intro")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                (
                    "public_slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        null=True,
                        unique=True,
                        verbose_name="Public slug",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="guides.guide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Translation",
                "db_table": "guides_guide_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuideItemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("teaser", models.TextField(blank=True, verbose_name="Teaser")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="guides.guideitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide Item Translation",
                "db_table": "guides_guideitem_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="guidesection",
            constraint=models.UniqueConstraint(
                fields=("guide", "order"), name="guidesection_order_unique_per_guide"
            ),
        ),
        migrations.AddIndex(
            model_name="guideitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="guides_guid_content_d1b58e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guidesectiontranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AlterUniqueTogether(
            name="guidetranslation",
            unique_together={("language_code", "master")},
        ),
    ]
