# Generated by Django 5.2.9 on 2026-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0004_alter_guide_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="is_starter",
            field=models.BooleanField(
                default=False,
                help_text="Shown first in the guide list and used as the homepage starter CTA.",
                verbose_name="Starter guide",
            ),
        ),
    ]
