# Generated by Django 5.2.9 on 2026-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0009_guide_approved_revision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guideitem",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Guide Item",
                "verbose_name_plural": "Guide Items",
            },
        ),
        migrations.AlterModelOptions(
            name="guidesection",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "Guide Section",
                "verbose_name_plural": "Guide Sections",
            },
        ),
    ]
