# Generated by Django 5.2.8 on 2025-11-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("double_opt_in", models.BooleanField(default=False)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_reason", models.CharField(blank=True, max_length=250)),
                ("source", models.CharField(blank=True, max_length=150)),
                ("tags", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doi_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
