"""
Django settings for mentoroai project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from typing import Iterable, List, Tuple
import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")

def env_bool(name: str, default: bool) -> bool:
    """
    Boolean env reader that accepts common truthy strings (1/true/yes/on)
    and falls back to a given default;
    used to toggle security flags without code changes.
    """
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.lower() in {"1", "true", "yes", "on"}

def _split_env(value: str, delimiter: str = ",") -> List[str]:
    """
    Utility to parse comma- or custom-delimited env strings into trimmed lists;
    avoids repeated split/strip patterns across settings.
    """
    return [item.strip() for item in value.split(delimiter) if item.strip()]


def _parse_admins(raw_admins: str) -> List[Tuple[str, str]]:
    """
    Parses DJANGO_ADMINS values like "Name:email;Name2:email2" into Django’s ADMINS structure;
    falls back to "Admin" when a name is missing and ignores empty emails.
    """
    entries: Iterable[str] = _split_env(raw_admins, ";")
    admins: List[Tuple[str, str]] = []
    for entry in entries:
        if ":" in entry:
            name, email = entry.split(":", 1)
        else:
            name, email = "Admin", entry
        if email:
            admins.append((name.strip() or "Admin", email.strip()))
    return admins


SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = _split_env(os.getenv("DJANGO_ALLOWED_HOSTS"))

default_csrf = "http://127.0.0.1:8000,http://localhost:8000"

if os.getenv("DJANGO_ENV") in {"ci", "test", "testing", "dev", "development"}:
    CSRF_TRUSTED_ORIGINS = _split_env(
        default_csrf
    )
else:
    CSRF_TRUSTED_ORIGINS = _split_env(
        os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS")
    )

ADMINS = _parse_admins(os.getenv("DJANGO_ADMINS", ""))
MANAGERS = ADMINS

# Application definition
INSTALLED_APPS = [
    # Django
    # "django.contrib.admin",
    "mentoroai.apps.MentoroAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    # Drittanbieter
    "rest_framework",
    "taggit",
    "imagekit",
    "django_celery_beat",
    "heroicons",
    "django_extensions",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.apple",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "easy_thumbnails",
    "filer",
    "tinymce",
    "django_fsm",
    "widget_tweaks",
    "parler",
    "reversion",
    "rules",
    # Projekt-Apps
    "accounts",
    "catalog",
    "content",
    "compare",
    "core.apps.CoreConfig",
    "guides",
    "glossary",
    "prompts",
    "usecases",
    "newsletter",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "mentoroai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.seo.context_processor.context_processor",
                "django.template.context_processors.i18n",
            ],
            "builtins": [
                "heroicons.templatetags.heroicons",
            ],
        },
    },
]

WSGI_APPLICATION = "mentoroai.wsgi.application"

# Database
SSL_REQUIRE = env_bool("DJANGO_DATABASE_SSL_REQUIRE", False)
if os.getenv("DJANGO_DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            env="DJANGO_DATABASE_URL",
            conn_max_age=600,
            ssl_require=SSL_REQUIRE,
        )
    }
else:
    DATABASES = {
        # "default": {
        #     "ENGINE": "django.db.backends.postgresql",
        #     "NAME": os.getenv("POSTGRES_DB", "mentoroai"),
        #     "USER": os.getenv("POSTGRES_USER", "postgres"),
        #     "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        #     "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        #     "PORT": os.getenv("POSTGRES_PORT", "5432"),
        # },
        "default": dj_database_url.config(
            # Replace this value with your local database's connection string.
            default='postgresql://postgres:postgres@localhost:5432/mentoroai',
            conn_max_age=600
        )
    }

# Für Tests auf SQLite umschalten (schneller, kein DB-Setup nötig)
if os.getenv("TEST_DB", "postgres") == "sqlite":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

TEST_RUNNER = "django.test.runner.DiscoverRunner"

# Internationalization

LANGUAGE_CODE = "en"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = (
    ("en", "English"),
    ("de", "Deutsch"),
)

PARLER_LANGUAGES = {
    1: (
        {'code': 'en', },
        {'code': 'de', },
    ),
    'default': {
        'fallback': 'en',  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,  # the default; let .active_translations() return fallbacks too.
    }
}
PARLER_DEFAULT_LANGUAGE_CODE = 'en'

LOCALE_PATHS = [BASE_DIR / "locale"]

STATIC_URL: str = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Hashed filenames + Gzip/Brotli ausliefern
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# TinyMCE Config

TINYMCE_DEFAULT_CONFIG = {
    "license_key": 'gpl',
    "menubar": False,
    "height": 540,
    "plugins": (
        "anchor autolink autoresize autosave charmap code codesample emoticons fullscreen image link lists "
        "media preview quickbars searchreplace table visualblocks visualchars insertdatetime wordcount"
    ),
    "style_formats_merge": False,
    "style_formats": [
        {
            "title": "Headings",
            "items": [
                {"title": "Heading 2", "format": "h2"},
                {"title": "Heading 3", "format": "h3"},
                {"title": "Heading 4", "format": "h4"},
            ],
        },
        {
            "title": "Inline",
            "items": [
                {"title": "Strikethrough", "format": "strikethrough"},
                {"title": "Superscript", "format": "superscript"},
                {"title": "Subscript", "format": "subscript"},
                {"title": "Code", "format": "code"},
            ],
        },
        {
            "title": "Blocks",
            "items": [
                {"title": "Paragraph", "format": "p"},
                {"title": "Blockquote", "format": "blockquote"},
                {"title": "Div", "format": "div"},
                {"title": "Pre", "format": "pre"},
            ],
        },
    ],
    "toolbar": (
        "fullscreen preview | undo redo | styles | bold italic underline removeformat | alignleft aligncenter alignright alignjustify |"
        "bullist numlist outdent indent | table | link image media charmap codesample | "
        "visualblocks visualchars | searchreplace emoticons wordcount "
    ),
    "table_toolbar": (
        "tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol"
    ),
    "visualblocks_default_state": True,
    "visualchars_default_state": True,
    "convert_urls": False,
    "automatic_uploads": True,
    "invalid_elements": "h1",
    "images_upload_credentials": True,
    "image_list": "/admin/tinymce/image-list/",
    # ---- WICHTIG: eigener Upload-Handler mit X-CSRFToken ----
    "images_upload_handler": """
        function (blobInfo, progress) {
          return new Promise(function (resolve, reject) {
            function getCookie(name) {
              const value = ('; ' + document.cookie).split('; ' + name + '=');
              if (value.length === 2) return value.pop().split(';').shift();
            }
            const xhr = new XMLHttpRequest();
            xhr.open('POST', '/admin/tinymce/upload/');
            xhr.setRequestHeader('X-CSRFToken', getCookie('csrftoken')); // <— wichtig
            xhr.upload.onprogress = function (e) {
              if (e.lengthComputable) { progress(Math.round(e.loaded / e.total * 100)); }
            };
            xhr.onload = function () {
              if (xhr.status !== 200) {
                reject('HTTP Error: ' + xhr.status + ' – ' + (xhr.responseText || ''));
                return;
              }
              try {
                const json = JSON.parse(xhr.responseText);
                if (!json || typeof json.location !== 'string') {
                  reject('Invalid JSON response');
                  return;
                }
                resolve(json.location);
              } catch (err) {
                reject('Invalid JSON: ' + err);
              }
            };
            xhr.onerror = function () { reject('Image upload failed due to a XHR Transport error.'); };
            const formData = new FormData();
            formData.append('file', blobInfo.blob(), blobInfo.filename());
            xhr.send(formData);
          });
        }
    """,
}

# Celery (einfaches Beispiel)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")

# DRF Basis
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

# --- SEO / Site Info ---
SITE_NAME = "MentoroAI"
SITE_URL = "https://www.mentoro-ai.com"
SITE_ID = int(os.getenv("SITE_ID", "1"))

AUTHENTICATION_BACKENDS = [
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",  # Django Default
    "allauth.account.auth_backends.AuthenticationBackend",  # allauth
]

# --- allauth Basiskonfiguration ---
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Optionen: "none" | "optional" | "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = {"email", "username"}

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "APP": {
            "client_id": os.getenv("GITHUB_CLIENT_ID", ""),
            "secret": os.getenv("GITHUB_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["user:email"],
    },
    "apple": {
        "APP": {
            "client_id": os.getenv("APPLE_CLIENT_ID", ""),
            # Das Secret erzeugen wir on-the-fly mit dem Management-Command und
            # tragen es anschließend im Admin in der SocialApp oder in env ein.
            "secret": os.getenv("APPLE_CLIENT_SECRET", ""),
            "key": "",
        },
    },
}

# E-Mail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DJANGO_DEFAULT_FROM_EMAIL")
SERVER_EMAIL = os.getenv("DJANGO_SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.getenv("DJANGO_EMAIL_SUBJECT_PREFIX", "[MentoroAI] ")
EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST")
EMAIL_PORT = os.getenv("DJANGO_EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env_bool("DJANGO_EMAIL_USE_TLS", False)
# EMAIL_USE_SSL = os.getenv("DJANGO_EMAIL_USE_SSL")
EMAIL_TIMEOUT = 60
# EMAIL_SSL_KEYFILE = os.getenv("DJANGO_EMAIL_SSL_KEYFILE")
# EMAIL_SSL_CERTFILE = os.getenv("DJANGO_EMAIL_SSL_CERTFILE")

# Editorial

EDITOR_GROUP_NAMES = ["Editors", "Admins"]

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
        }
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "mentoroai_cache_table",
    }
}
