# Generated by Django 5.2.8 on 2025-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_tool_monthly_price_min_and_more"),
        ("prompts", "0002_remove_prompt_reviewer_alter_prompt_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the AI tool for which this prompt has been optimized.",
                related_name="prompts",
                to="catalog.tool",
            ),
        ),
    ]
