# Generated by Django 5.2.9 on 2025-12-12 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0004_alter_prompt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
