# Generated by Django 5.2.8 on 2025-11-11 22:14

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Term"
                    ),
                ),
                ("slug", models.SlugField(max_length=150, verbose_name="Slug")),
                (
                    "translation_group",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                ("short_definition", models.TextField(verbose_name="Short definition")),
                (
                    "long_definition",
                    models.TextField(blank=True, verbose_name="Long definition"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en",
                        max_length=50,
                        verbose_name="Language",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Glossary term",
                "verbose_name_plural": "Glossary terms",
                "ordering": ["term"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "language"), name="uniq_glossary_slug_language"
                    ),
                    models.UniqueConstraint(
                        fields=("translation_group", "language"),
                        name="uniq_glossary_group_language",
                    ),
                ],
            },
        ),
    ]
