# Generated by Django 5.2.9 on 2026-08-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossaryterm",
            options={
                "ordering": ("term",),
                "verbose_name": "Glossary term",
                "verbose_name_plural": "Glossary terms",
            },
        ),
    ]
