# Generated by Django 5.2.8 on 2025-12-03 21:26

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0002_remove_comparison_reviewer_alter_comparison_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("rework", "Rework"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=50,
                protected=True,
            ),
        ),
    ]
