# Generated by Django 5.2.9 on 2025-12-12 14:46

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_tool_slug"),
        ("compare", "0004_alter_comparison_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comparison",
            options={
                "ordering": ("-published_at", "-updated_at"),
                "verbose_name": "Tool comparison",
                "verbose_name_plural": "Tool comparisons",
            },
        ),
        migrations.AlterModelOptions(
            name="comparisontranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Tool comparison Translation",
            },
        ),
        migrations.RemoveField(
            model_name="comparison",
            name="score_breakdown",
        ),
        migrations.RemoveField(
            model_name="comparison",
            name="winner",
        ),
        migrations.AddField(
            model_name="comparison",
            name="live_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="comparisontranslation",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Optional longer text with context, recommendations or wrap-up.",
                verbose_name="Body",
            ),
        ),
        migrations.AddField(
            model_name="comparisontranslation",
            name="public_slug",
            field=models.SlugField(
                blank=True,
                help_text="Optional public slug. If empty, slug will be used on publish.",
                max_length=220,
                null=True,
                unique=True,
                verbose_name="Public slug",
            ),
        ),
        migrations.AlterField(
            model_name="comparisontranslation",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="Short introduction shown in lists and above the comparison.",
                verbose_name="Intro",
            ),
        ),
        migrations.AlterField(
            model_name="comparisontranslation",
            name="slug",
            field=models.SlugField(
                help_text="Internal slug, used for the default detail URL.",
                max_length=220,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.CreateModel(
            name="ComparisonToolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which tools are displayed in this comparison.",
                    ),
                ),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_entries",
                        to="compare.comparison",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_entries",
                        to="catalog.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool comparison entry",
                "verbose_name_plural": "Tool comparison entries",
                "ordering": ("position", "pk"),
                "unique_together": {("comparison", "tool")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='tools',
        ),
        migrations.AddField(
            model_name='comparison',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                related_name='comparisons',
                through='compare.ComparisonToolEntry',
                to='catalog.tool',
            ),
        ),
        migrations.CreateModel(
            name="ComparisonToolEntryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional headline for this tool within the comparison.",
                        max_length=200,
                        verbose_name="Label / heading",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Free text: main description for this tool in the comparison.",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "pros",
                    models.TextField(
                        blank=True,
                        help_text="Use bullet lists in TinyMCE to highlight strengths.",
                        verbose_name="Strengths / advantages",
                    ),
                ),
                (
                    "cons",
                    models.TextField(
                        blank=True,
                        help_text="Use bullet lists in TinyMCE to highlight weaknesses.",
                        verbose_name="Weaknesses / limitations",
                    ),
                ),
                (
                    "special",
                    models.TextField(
                        blank=True,
                        help_text="Anything unique, edge cases, or important caveats.",
                        verbose_name="Special features / notes",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="compare.comparisontoolentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool comparison entry Translation",
                "db_table": "compare_comparisontoolentry_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
