# Generated by Django 5.2.9 on 2026-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0005_alter_comparison_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
