# Generated by Django 5.2.9 on 2026-07-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0006_alter_comparison_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="live_entries",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
