# Generated by Django 5.2.8 on 2025-11-22 19:23

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_tool_created_at_tool_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={
                "ordering": ("-updated_at", "-pk"),
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
            },
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="features",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="name",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="price_month",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="price_year",
        ),
        migrations.CreateModel(
            name="PricingTierTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "price_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "price_year",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.pricingtier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing tier Translation",
                "db_table": "catalog_pricingtier_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
