# Generated by Django 5.2.8 on 2025-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_tool_options_remove_pricingtier_features_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="monthly_price_min",
        ),
        migrations.AlterField(
            model_name="tool",
            name="pricing_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Completely free"),
                    ("freemium", "Freemium (free basic, paid pro)"),
                    ("subscription", "Subscription (monthly/yearly)"),
                    ("payg", "Pay-as-you-go / usage-based"),
                    ("license", "One-time license / lifetime deal"),
                    ("opensource", "Open-source / self-hosted"),
                    ("custom", "Contact sales / custom pricing"),
                    ("other", "Other / mixed model"),
                ],
                max_length=32,
            ),
        ),
    ]
