# Generated by Django 5.2.8 on 2025-11-28 15:41

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Tool = apps.get_model("catalog", "Tool")
    ToolTranslation = apps.get_model("catalog", "ToolTranslation")

    for tool in Tool.objects.all():
        if getattr(tool, "slug", None):
            continue

        tr = (ToolTranslation.objects.filter(master_id=tool.pk, language_code="en").first() or ToolTranslation.objects.filter(
            master_id=tool.pk).first())

        if tr and tr.name:
            base = tr.name
        else:
            base = f"tool-{tool.pk}"

        slug = slugify(base)[:220]

        orig = slug
        i = 2
        while (
                Tool.objects.filter(slug=slug)
                        .exclude(pk=tool.pk)
                        .exists()
        ):
            suffix = f"-{i}"
            slug = orig[: 220 - len(suffix)] + suffix
            i += 1

        tool.slug = slug
        tool.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_remove_tool_monthly_price_min_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="tooltranslation",
                    name="slug",
                ),
            ],
            database_operations=[
                migrations.RemoveField(
                    model_name="tooltranslation",
                    name="slug",
                ),
            ],
        ),

        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(
                max_length=220,
                unique=True,
                null=True,
                blank=True,
                verbose_name="Slug",
            ),
        ),

        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
    ]
