# Generated by Django 5.2.8 on 2025-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_tooltranslation_slug_tool_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="slug",
            field=models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
        ),
    ]
